apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/matt-a-gill-me-com/scm-devdb:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/matt-a-gill-me-com/scm-devdb:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: scm-devdb
        chartPath: charts/scm-devdb
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/matt-a-gill-me-com/scm-devdb"
          image.tag: "{{.TAG}}"
