# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 10.35.251.64:5000/matt-a-gill-me-com/scm-devdb
  tag: 0.0.3
  pullPolicy: IfNotPresent
service:
  name: scm-devdb
  type: ClusterIP
  externalPort: 3306
  internalPort: 3306
resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
terminationGracePeriodSeconds: 10
